config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  scope :format => true, :constraints => { :format => /json/ } do
    resources :summaries,  :only => [:show]
  end

  mount ActionCable.server => '/cable'

  scope :constraints => AuthenticatedConstraint.new do

    resources :characters, except: [:destroy] do
      scope module: 'characters' do
        resources :builds,  except: [:new] do
          resources :build_aspects,     except: %i(index show)
          resources :build_attributes,  except: %i(index show)
          resources :build_essays,      except: %i(index show)
          resources :build_items,       except: %i(index show)
          resources :build_properties,  except: %i(index show)
          resources :build_ranks,       except: %i(index show)
        end
        resources :game_sessions, except: %i(new)
        resources :sheets,        except: %i(new edit)
      end
    end

    namespace :api do
      resources :systems, only: %i(index) do
        scope module: 'systems' do
          resources :traits,      only: %i(show index)
        end
      end
    end

    resources :user_items, except: %i(show)

    get '/logout', :to => 'sessions#destroy'

    root :to => 'characters#index'
  end

  scope :constraints => AdminAuthenticatedConstraint.new do

    mount DocServer.new => '/docs'    if Rails.application.config.yard_server               == :enabled
    mount Sidekiq::Web  => '/sidekiq' if Rails.application.config.active_job.queue_adapter  == :sidekiq

    resources :systems, only: %i(index show new create), shallow: true do
      scope module: 'systems' do
        resources :build_calculations, except: %i(destroy show)
        resources :categories,         except: %i(destroy show)
      end
    end

    resources :systems, only: %i(index show new create) do
      scope module: 'systems' do
        resources :traits, except: %i(destroy show)
      end
    end

    get '/admin', :to => 'systems#index'
  end

  post '/login', :to => 'sessions#create'

  scope :constraints => lambda { |r| r.env['warden'].user.nil? } do
    get '/', :to => 'sessions#new'
  end

  match '(*)', :via => [:get, :post, :put, :delete, :patch],
               :to  => proc { [404, {}, ['']] }, :as => :not_found
end

app/views/layouts/_character_navbar.html.erb
<% cache character do %>
  <nav role="navigation">
    <h4><%= character.name %></h4>
    <ul class="nav nav-stacked nav-pills nav-fill">
      <li role="presentation"><%= link_to('Overview', character)%></li>
      <li role="presentation"><%= link_to('Build', character_builds_path(character)) %></li>
      <li role="presentation"><%= link_to('Game Sessions', character_game_sessions_path(character)) %></li>
      <li role="presentation"><%= link_to('Sheets', character_sheets_path(character)) %></li>
      <li role="presentation"><%= link_to('Update', [:edit, character]) %></li>
      <li role="presentation"><a href="/logout">Logout</a></li>
    </ul>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<head>
  <title>Tamori</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
</head>

app/views/layouts/_system_navbar.html.erb
<% cache system do %>
  <ul class="nav nav-stacked nav-pills nav-fill">
    <h4><%= system.name %></h4>
    <li role="presentation"><%= link_to('Overview', system) %></li>
    <li role="presentation"><%= link_to('Categories', system_categories_path(system)) %></li>
    <li role="presentation"><%= link_to('Traits', system_traits_path(system)) %></li>
    <li role="presentation"><%= link_to('Calculations', system_build_calculations_path(system)) %></li>
    <li role="presentation"><a href="/logout" class="danger">Logout</a></li>
  </ul>
<% end %>

app/views/layouts/_user_navbar.html.erb
<ul class="nav nav-stacked nav-pills nav-fill">
  <h4><%= current_user_name %></h4>
  <% if current_user_admin? %>
    <li role="presentation"><%= link_to('Systems', systems_path)%></li>
  <% end %>
  <li role="presentation"><%= link_to 'Characters', root_url %></li>
  <li role="presentation"><%= link_to('Items', user_items_path) %></li>
  <li role="presentation"><a href="/logout" class="danger">Logout</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-ng-app="tamoriApp">
  <%= render partial: 'layouts/header' %>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div id="navigation" class="col-xs-12 col-md-2 bg-info">
          <%= render partial: 'layouts/user_navbar' %>
        </div>
        <div class="col-xs-12 col-md-10">
            <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/character.html.erb
<!DOCTYPE html>
<html data-ng-app="tamoriApp">
  <%= render partial: 'layouts/header' %>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div id="navigation" class="col-xs-12 col-md-2 bg-info">
          <%= render partial: 'layouts/character_navbar', locals: { character: local_assigns[:character] } %>
        </div>
        <div class="col-xs-12 col-md-10">
          <div class="row">
            <div class="col-xs-12">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/system.html.erb
<!DOCTYPE html>
<html data-ng-app="tamoriApp">
  <%= render partial: 'layouts/header' %>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div id="navigation" class="col-xs-12 col-md-2 bg-info">
          <%= render partial: 'layouts/system_navbar', locals: { system: local_assigns[:system] } %>
        </div>
        <div class="col-xs-12 col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>